### ISSUE TITLE
have any plan to support Open AI API directly?

### ISSUE THREAD

**Issue by imzjy** [cyyyu/ai#1]
It appears it only work with Azure Open AI API interface, do you have any plan to support Open AI API directly?

**Comment by cyyyu** [comment]
@imzjy no plan for it yet as I found a few other projects have already done a great job with it when I started this one. such as https://github.com/peterdemin/openai-cli.
it's nice to have though. PRs are always welcome.

**Comment by imzjy** [comment]
@cyyyu thanks for the reply! it looks like the mentioned openai-cli design towards the interactive usage. for those who want use ChatGPT as automation tools, i discovered: https://github.com/kardolus/chatgpt-cli
